version: "2"

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web.docker
    volumes:
      - ./:/var/www

    ports:
      - "9700:80"

    links:
      - app

  app:
    build:
      context: ./
      dockerfile: ./docker/app.docker
    volumes:
      - ./:/var/www

    links:
      - database
      - mongo
      - redis
      - elasticsearch

#    environment:
#      - "DB_PORT=3306"
#      - "DB_HOST=127.0.0.1"
#      - "DB_USERNAME=root"
#      - "DB_PASSWORD=secret"

  database:
    container_name: "pipein_db"
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root

    ports:
      - "33061:3306"

  mongo:
    image: mongo
    container_name: "pipein_mongo"
    ports:
      - "27018:27017"

  redis:
    image: redis
    ports:
      - "63791:6379"

  elasticsearch:
    image: elasticsearch
    container_name: "pipein_search"
    ports:
      - "9201:9200"
      - "9301:9300"



