version: "2"

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web.docker
    volumes:
      - ./:/var/www

    ports:
      - "9700:80"

    links:
      - app

  app:
    build:
      context: ./
      dockerfile: ./docker/app.docker
    volumes:
      - ./:/var/www

    links:
      - database
      - mongo
      - redis
      - elasticsearch


  database:
    container_name: "pipein_db"
    image: mysql:5.7
    hostname: database
    environment:
      - MYSQL_DATABASE=pipein
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret

    ports:
      - 3306

  mongo:
    image: mongo
    hostname: mongo
    container_name: "pipein_mongo"
    ports:
      - 27017

  redis:
    image: redis
    hostname: redis
    ports:
      - 6379

  elasticsearch:
    image: elasticsearch
    hostname: elasticsearch
    container_name: "pipein_search"
    ports:
      - 9200
      - 9300



